
# html lang
language: en

# main menu navigation
menu:
  Home: /
  About: /about
  Links: /links
  Archives: /archives

# stylesheets loaded in the <head>
stylesheets:
- /css/acanal.css
- /css/highlight.css

# scripts loaded in the end of the body
scripts:
- /js/acanal.js
