
# html lang
language: en

# main menu navigation
menu:
  Home: /
  About: /about
  Links: /links
  Archives: /archives

# stylesheets loaded in the <head>
stylesheets:
- /css/acanal.css
- /css/responsive.css
- /css/highlight.css

# scripts loaded in the end of the body
scripts:
- /js/acanal.js

# Valine
valine:
  enable: false # true
  el: 'vcomments'
  appId: 
  appKey: 
  notify: false
  verify: false
  avatar: 'mp'
  pageSize: '10'
  placeholder: '请输入...' 
  visitor: true

mathjax:
  enable: true
  cdn: https://lib.baomitu.com/mathjax/2.7.6/MathJax.js?config=TeX-AMS-MML_HTMLorMML
